import Navbar from '@/components/ui-components/Navbar'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="w-full relative h-screen p-4">
        <Navbar/>
        {children}</body>
    </html>
  )
}
